# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_source',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
