# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170511_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unsplash_image',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
