# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_source',
        ),
        migrations.AlterField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=630),
        ),
        migrations.AlterField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=1400),
        ),
    ]
