# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_unsplash_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unsplash_image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_size',
            field=models.CharField(blank=True, choices=[('800x350', 'Snall (800x350)'), ('1200x630', 'Medium (1200x630)'), ('1600x900', 'Large (1600x900)')], max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
