# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170522_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
