# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
