# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170515_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unsplash_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
