# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
