# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('euros', models.CharField(blank=True, max_length=500, null=True)),
                ('comments', models.CharField(blank=True, max_length=900, null=True)),
                ('euros_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('xrate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dollars_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_savings_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('daily_savings_display', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MonthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.CharField(blank=True, max_length=500, null=True)),
                ('total_spent_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_spent_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_savings_display', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_spent_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_savings_display', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
