# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_list', models.CharField(max_length=500)),
                ('dollars', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('euros', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='detailedentry',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argent.Entry'),
        ),
    ]
