# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='currency',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
