# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', '(EUR) Euro'), ('USD', '(USD) US Dollar'), ('GBP', '(GBP) United Kingdom Pound'), ('CZK', '(CZK) Czech Republic Koruna'), ('HUF', '(HUF) Hungary Forint'), ('CHF', '(CHF) Swiss Franc')], max_length=900, null=True),
        ),
    ]
