# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0002_entry_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='currency',
        ),
    ]
