# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0002_auto_20170502_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
