# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0003_auto_20170505_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='daily_savings_display',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='daily_savings_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='spending_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='xrate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
