# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0003_remove_entry_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CZK', 'CZK'), ('HUF', 'HUF')], max_length=900, null=True),
        ),
    ]
