# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0004_auto_20170531_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', '(USD) US Dollar'), ('EUR', '(EUR) Euro'), ('GBP', '(GBP) United Kingdom Pound'), ('CZK', '(CZK) Czech Republic Koruna'), ('HUF', '(HUF) Hungary Forint'), ('CHF', '(CHF) Swiss Franc')], max_length=900, null=True),
        ),
    ]
