# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0004_entry_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'United Kingdom Pound'), ('CZK', 'Czech Republic Koruna'), ('HUF', 'Hungary Forint')], max_length=900, null=True),
        ),
    ]
