# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0006_auto_20180420_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Location',
        ),
    ]
