# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0008_auto_20170309_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='euros_total',
            new_name='euros_sum',
        ),
    ]
