# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0009_auto_20180420_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='location',
            new_name='country',
        ),
    ]
