# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0009_auto_20170309_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='euros_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
