# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0010_auto_20170427_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='xrate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
