# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0010_auto_20170309_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='xrate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
