# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0011_entry_xrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
