# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0011_auto_20180421_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='argent.Country'),
        ),
    ]
