# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0012_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='country',
        ),
        migrations.AddField(
            model_name='entry',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='argent.City'),
        ),
    ]
