# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0013_auto_20170309_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dollars_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
