# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0014_entry_dollars_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dollars_sum',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='euros_sum',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
