# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0015_auto_20170310_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent_euros', models.CharField(max_length=500)),
                ('total_spent_dollars', models.CharField(max_length=500)),
                ('total_savings_euros', models.CharField(max_length=500)),
                ('total_savings_dollars', models.CharField(max_length=500)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argent.Entry')),
            ],
        ),
        migrations.RemoveField(
            model_name='detailedentry',
            name='date',
        ),
        migrations.DeleteModel(
            name='DetailedEntry',
        ),
    ]
