# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0017_auto_20170313_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='total_savings_dollars',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_savings_euros',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_spent_dollars',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_spent_euros',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
