# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0018_auto_20170314_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='daily_savings_dollars',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='daily_savings_euros',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
