# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0021_auto_20170314_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='daily_savings_dollars',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='dollars_sum',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='euros',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='euros_sum',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='xrate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
