# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0029_auto_20170315_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='total_savings_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_savings_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_spent_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_spent_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
