# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0030_auto_20170320_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='total_spent_euros',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
