# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0031_auto_20170320_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='date',
        ),
    ]
