# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0032_remove_savings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='total_spent_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
