# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0033_auto_20170320_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='total_savings_dollars',
            new_name='total_savings',
        ),
    ]
