# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0034_auto_20170320_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='total_savings_euros',
        ),
    ]
