# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0035_remove_savings_total_savings_euros'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='daily_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
