# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0036_entry_daily_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argent.Entry'),
        ),
    ]
