# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0039_auto_20170321_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='daily_savings_display',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
