# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0040_auto_20170321_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='total_savings_display',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
