# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0041_savings_total_savings_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
