# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0042_savings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='date',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='argent.Entry'),
            preserve_default=False,
        ),
    ]
