# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0043_auto_20170322_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='total_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_savings_display',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_spent_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='total_spent_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
