# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0044_auto_20170323_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='date',
        ),
        migrations.AddField(
            model_name='entry',
            name='total_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_savings_display',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_spent_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_spent_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name='Savings',
        ),
    ]
