# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0045_auto_20170323_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_spent_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_savings_display', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='total_savings',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='total_savings_display',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='total_spent_dollars',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='total_spent_euros',
        ),
        migrations.AddField(
            model_name='savings',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argent.Entry'),
        ),
    ]
