# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0047_auto_20170323_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months_Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.CharField(blank=True, max_length=500, null=True)),
                ('total_spent_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_spent_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_savings_display', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
