# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0048_months_years'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Months_Years',
            new_name='MonthsYears',
        ),
    ]
