# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0049_auto_20170324_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthsYears',
            new_name='MonthYear',
        ),
    ]
