# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argent', '0050_auto_20170324_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='savings',
            name='date',
        ),
    ]
