# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
