# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='unsplash_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
