# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190123_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='height_field',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='about',
            name='width_field',
            field=models.IntegerField(default=1440),
        ),
    ]
