# Generated by Django 2.1 on 2019-06-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.CharField(blank=True, max_length=120)),
                ('rating', models.CharField(blank=True, max_length=120, null=True)),
                ('review', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Yelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=120, null=True)),
                ('link', models.CharField(max_length=120)),
                ('scrape_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='results',
            name='yelp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.Yelp'),
        ),
    ]
