# Generated by Django 2.1 on 2019-08-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_auto_20190730_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelp',
            name='scrape_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
